const SUCCESS = 200
const AUTHORIZATION = 401
const NOT_FOUND = 404
const BAD_REQUEST = 400
const SERVER_ERROR = 500
const SERVICE_UNAVAILABLE = 503

export default {
  SUCCESS,
  AUTHORIZATION,
  NOT_FOUND,
  BAD_REQUEST,
  SERVER_ERROR,
  SERVICE_UNAVAILABLE
}
